### ISSUE TITLE
Add in Readme to Work on gh-pages rather than on master.

### ISSUE THREAD

**Issue by stalwart201** [stalwart201/Django-basics#15]
@realslimshanky do it. And mention that to do work in gh-pages branch only no commits will be merged in master from now.
Give a brief about how to clone specific branch locally and start working on it.

**Comment by realslimshanky** [comment]
Working on it..!!

**Comment by stalwart201** [comment]
Status?

**Comment by stalwart201** [comment]
Thanks. @realslimshanky
